Added: source rc.site, is_true function, and code to clean /tmp, process /etc/sysconfig/createfiles, copy early udev rules from /run, process /etc/sysconfig/udev_retry.

diff --git a/trunk/1 b/trunk/1
--- a/trunk/1
+++ b/trunk/1
@@ -41,6 +41,17 @@ msg "Welcome to Linux From Scratch! \n"
 # to load optional system preferences.
 . /etc/runit.conf
 
+# The LFS rc.site file contains parameters and system variables that can customize various
+# aspects of the boot process.
+. /etc/sysconfig/rc.site &>/dev/null
+
+# A function from init-functions.
+is_true()
+{
+   [ "$1" = "1" ] || [ "$1" = "yes" ] || [ "$1" = "true" ] ||
+   [ "$1" = "y" ] || [ "$1" = "t" ]
+}
+
 # Let's mount the kernel virtual file systems here. In the past mountvirtfs was used to do this.
 # This section reduplicates this functionality and simplifies the process. This will read fstab
 # properly and mount according to the triggers specificed.
@@ -145,7 +156,6 @@ msg "Mounting rootfs read-write...\n"
 mount -o remount,rw /
 
 # Start the system and kernel log daemons.
-. /etc/sysconfig/rc.site
 parms=${SYSKLOGD_PARMS-'-m 0'}
 msg "Starting system and kernel log daemons...\n"
 syslogd $parms &>/dev/null
@@ -154,6 +164,73 @@ klogd &>/dev/null
 # Any non-networked file systems will now be mounted.
 msg "Mounting all non-network filesystems...\n"
 mount -a -t "nosysfs,nonfs,nonfs4,nosmbfs,nocifs" -O no_netdev
+
+# Clean /tmp.
+msg "Cleaning up /tmp...\n"
+if ! is_true "$SKIPTMPCLEAN" ; then
+    cd /tmp
+    find . -xdev -mindepth 1 ! -name lost+found -delete &>/dev/null
+fi
+
+# Create files and directories specified in /etc/sysconfig/createfiles.
+msg "Processing /etc/sysconfig/createfiles...\n"
+if egrep -qv '^(#|$)' /etc/sysconfig/createfiles &>/dev/null ; then
+   exec 9>&0 < /etc/sysconfig/createfiles
+   while read name type perm usr grp dtype maj min junk ; do
+      # Ignore comments and blank lines.
+      case "${name}" in
+         ""|\#*) continue ;;
+      esac
+      # Ignore existing files.
+      if [ ! -e "${name}" ]; then
+         # Create files and dirs.
+         case "${type}" in
+            dir)
+               mkdir "${name}" ;;
+            file)
+               :> "${name}" ;;
+            dev)
+               case "${dtype}" in
+                  char)
+                     mknod "${name}" c ${maj} ${min} ;;
+                  block)
+                     mknod "${name}" b ${maj} ${min} ;;
+                  pipe)
+                     mknod "${name}" p ;;
+                  *) 
+                     echo -e "/etc/sysconfig/createfiles: Unknown device type: ${dtype}" ;;
+               esac ;;
+            *)
+               echo -e "/etc/sysconfig/createfiles: Unknown type: ${type}"
+               continue ;;
+         esac
+         # Set permissions.
+         chown ${usr}:${grp} "${name}"
+         chmod ${perm} "${name}"
+      fi
+   done
+   # Close file descriptor 9 (end redirection)
+   exec 0>&9 9>&-
+fi
+
+# Copy udev rules generated before / was mounted rw.
+msg "Copying udev rules to /etc/udev/rules.d...\n"
+for file in /run/udev/tmp-rules--* ; do
+    dest=${file##*tmp-rules--}
+    [ "$dest" = '*' ] && break
+    cat $file >> /etc/udev/rules.d/$dest
+    rm -f $file
+done
+
+# Re-trigger subsystems listed in /etc/sysconfig/udev_retry.
+msg "Processing /etc/sysconfig/udev_retry...\n"
+sed -e 's/#.*$//' /etc/sysconfig/udev_retry | grep -v '^$' | \
+while read line ; do
+   for subsystem in $line ; do
+      udevadm trigger --subsystem-match=$subsystem --action=add &>/dev/null
+      udevadm settle &>/dev/null      
+   done
+done
 
 # If we have CGroups, this will load them.
 mountpoint -q /sys/fs/cgroup || mount -t tmpfs cgroup /sys/fs/cgroup -o mode=0755
@@ -214,3 +291,4 @@ install -m0 /dev/null /etc/runit/reboot
 install -m0 /dev/null /etc/runit/stopit
 
 msg "Initialization complete, running stage 2... \n"
+sleep 3
